name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  melodic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare test ROS package
        uses: actions/checkout@v2
        with:
          repository: 'Tiryoh/co2_sensor_driver_ros'
          path: 'co2_sensor_driver_ros'

      - name: Prepare for Cross-Build
        run: |
          sudo apt-get install -y qemu-user-static

      - name: Prepare Docker
        run: |
          echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json > /dev/null
          mkdir ~/.docker
          echo '{"experimental": "enabled"}' | tee -a ~/.docker/config.json > /dev/null
          sudo service docker restart

      - name: amd64
        continue-on-error: true
        id: amd64
        run: |
          cd ${GITHUB_WORKSPACE}/co2_sensor_driver_ros
          ${GITHUB_WORKSPACE}/run.sh /release_binary.sh
          echo ::set-output name=paths::$(ls release/*amd64.deb)
        env:
          ROS_DISTRO: melodic
          ARCH: amd64

      - name: arm64
        continue-on-error: true
        id: arm64
        run: |
          cd ${GITHUB_WORKSPACE}/co2_sensor_driver_ros
          ${GITHUB_WORKSPACE}/run.sh /release_binary.sh
          echo ::set-output name=paths::$(ls release/*arm64.deb)
        env:
          ROS_DISTRO: melodic
          ARCH: arm64

      - name: armhf
        continue-on-error: true
        id: armhf
        run: |
          cd ${GITHUB_WORKSPACE}/co2_sensor_driver_ros
          ${GITHUB_WORKSPACE}/run.sh /release_binary.sh
          echo ::set-output name=paths::$(ls release/*armhf.deb)
        env:
          ROS_DISTRO: melodic
          ARCH: armhf
