name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros-distro: [melodic, dashing]
        arch: [amd64, arm64, armhf]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare test ROS package
        uses: actions/checkout@v2
        with:
          repository: 'ros/ros_tutorials'
          ref: '${{ matrix.ros-distro }}-devel'
          path: 'ros_tutorials'

      - name: Setup QEMU for Cross-Build
        uses: docker/setup-qemu-action@v1.2.0

      - name: Run bloom-generate
        id: binary
        run: |
          cd ${GITHUB_WORKSPACE}/ros_tutorials
          ${GITHUB_WORKSPACE}/run.sh "cd turtlesim && /release_binary.sh"
          echo ::set-output name=paths::$(ls turtlesim/release/*.deb)
        env:
          ROS_DISTRO: ${{ matrix.ros-distro }}
          ARCH: ${{ matrix.arch }}

      - name: Output binary name
        run: |
          echo ${{ steps.binary.outputs.paths }}
